// ============================================================================
// Sample data — realistic Las Vegas properties + a buyers list
// ============================================================================
// Lets the entire platform be explored before any live data source is wired
// in. Replaced by RentCast / MLS / public-records feeds in production. The
// numbers are illustrative, not real listings.

import type { Property, Buyer } from "./types";

const now = new Date();
const iso = (daysAgo: number) =>
  new Date(now.getTime() - daysAgo * 86_400_000).toISOString();
const isoDate = (daysAgo: number) => iso(daysAgo).slice(0, 10);

export const SAMPLE_PROPERTIES: Property[] = [
  {
    id: "lv-001",
    address: "4821 Sunbird Ave",
    city: "Las Vegas",
    state: "NV",
    zip: "89110",
    lat: 36.1716,
    lng: -115.0573,
    propertyType: "single_family",
    beds: 3,
    baths: 2,
    sqft: 1480,
    lotSqft: 6100,
    yearBuilt: 1992,
    listPrice: 268_000,
    daysOnMarket: 74,
    status: "active",
    listingRemarks:
      "Estate sale, sold as-is. Original kitchen and flooring, dated bathrooms. Solid bones, motivated family wants a quick close. Great investor opportunity.",
    photos: [],
    priceHistory: [
      { date: isoDate(74), price: 289_000, event: "listed" },
      { date: isoDate(40), price: 279_000, event: "price_change" },
      { date: isoDate(12), price: 268_000, event: "price_change" },
    ],
    comps: [
      { address: "4850 Sunbird Ave", soldPrice: 332_000, soldDate: isoDate(35), beds: 3, baths: 2, sqft: 1500, distanceMiles: 0.1 },
      { address: "1290 Robin St", soldPrice: 345_000, soldDate: isoDate(60), beds: 3, baths: 2, sqft: 1520, distanceMiles: 0.3 },
      { address: "4710 Lark Ln", soldPrice: 318_000, soldDate: isoDate(80), beds: 3, baths: 2, sqft: 1450, distanceMiles: 0.4 },
    ],
    distressSignals: ["estate_sale", "long_dom", "major_price_reduction", "motivated_seller"],
    dealKillers: [],
    crimeScore: 52,
    schoolScore: 58,
    floodZone: false,
    neighborhoodGrowth: 6,
    rentalDemand: 72,
    investorCompetition: 38,
    estimatedRentMonthly: 1850,
    firstSeen: iso(12),
    lastScanned: iso(0),
  },
  {
    id: "lv-002",
    address: "7344 Desert Marigold Dr",
    city: "Las Vegas",
    state: "NV",
    zip: "89149",
    lat: 36.2741,
    lng: -115.2891,
    propertyType: "single_family",
    beds: 4,
    baths: 3,
    sqft: 2210,
    lotSqft: 7200,
    yearBuilt: 2004,
    listPrice: 392_000,
    daysOnMarket: 9,
    status: "active",
    listingRemarks:
      "Move-in ready, tastefully updated kitchen and floors. Pride of ownership. Won't last.",
    photos: [],
    priceHistory: [{ date: isoDate(9), price: 392_000, event: "listed" }],
    comps: [
      { address: "7360 Desert Marigold Dr", soldPrice: 415_000, soldDate: isoDate(25), beds: 4, baths: 3, sqft: 2240, distanceMiles: 0.1 },
      { address: "7201 Cactus Bloom Ct", soldPrice: 408_000, soldDate: isoDate(45), beds: 4, baths: 3, sqft: 2190, distanceMiles: 0.5 },
    ],
    distressSignals: [],
    dealKillers: [],
    crimeScore: 81,
    schoolScore: 76,
    floodZone: false,
    neighborhoodGrowth: 8,
    rentalDemand: 65,
    investorCompetition: 74,
    estimatedRentMonthly: 2400,
    firstSeen: iso(2),
    lastScanned: iso(0),
  },
  {
    id: "lv-003",
    address: "3155 Vegas Valley Dr #12",
    city: "Las Vegas",
    state: "NV",
    zip: "89121",
    lat: 36.1447,
    lng: -115.0876,
    propertyType: "condo",
    beds: 2,
    baths: 2,
    sqft: 980,
    lotSqft: 0,
    yearBuilt: 1985,
    listPrice: 158_000,
    daysOnMarket: 121,
    status: "active",
    listingRemarks:
      "Bank-owned REO. Needs cosmetic updating — carpet, paint, fixtures. Cash or hard money. Priced to move.",
    photos: [],
    priceHistory: [
      { date: isoDate(121), price: 185_000, event: "listed" },
      { date: isoDate(80), price: 172_000, event: "price_change" },
      { date: isoDate(30), price: 158_000, event: "price_change" },
    ],
    comps: [
      { address: "3155 Vegas Valley Dr #4", soldPrice: 205_000, soldDate: isoDate(40), beds: 2, baths: 2, sqft: 985, distanceMiles: 0.0 },
      { address: "3200 Sunrise Ave #8", soldPrice: 198_000, soldDate: isoDate(55), beds: 2, baths: 2, sqft: 960, distanceMiles: 0.3 },
    ],
    distressSignals: ["reo", "long_dom", "major_price_reduction"],
    dealKillers: [],
    crimeScore: 44,
    schoolScore: 49,
    floodZone: false,
    neighborhoodGrowth: 4,
    rentalDemand: 80,
    investorCompetition: 30,
    estimatedRentMonthly: 1350,
    firstSeen: iso(30),
    lastScanned: iso(0),
  },
  {
    id: "lv-004",
    address: "609 Bonanza Crest St",
    city: "North Las Vegas",
    state: "NV",
    zip: "89030",
    lat: 36.2008,
    lng: -115.1228,
    propertyType: "single_family",
    beds: 3,
    baths: 2,
    sqft: 1320,
    lotSqft: 5800,
    yearBuilt: 1978,
    listPrice: 215_000,
    daysOnMarket: 95,
    status: "active",
    listingRemarks:
      "Pre-foreclosure, owner motivated. Some settling noted on inspection, possible foundation movement. Sold strictly as-is.",
    photos: [],
    priceHistory: [
      { date: isoDate(95), price: 235_000, event: "listed" },
      { date: isoDate(45), price: 215_000, event: "price_change" },
    ],
    comps: [
      { address: "640 Bonanza Crest St", soldPrice: 268_000, soldDate: isoDate(50), beds: 3, baths: 2, sqft: 1340, distanceMiles: 0.1 },
      { address: "588 Statz St", soldPrice: 255_000, soldDate: isoDate(70), beds: 3, baths: 2, sqft: 1300, distanceMiles: 0.4 },
    ],
    distressSignals: ["pre_foreclosure", "long_dom", "motivated_seller"],
    dealKillers: ["foundation"],
    crimeScore: 35,
    schoolScore: 41,
    floodZone: false,
    neighborhoodGrowth: 3,
    rentalDemand: 70,
    investorCompetition: 42,
    estimatedRentMonthly: 1500,
    firstSeen: iso(20),
    lastScanned: iso(0),
  },
  {
    id: "lv-005",
    address: "2914 Palm Crescent Ln",
    city: "Henderson",
    state: "NV",
    zip: "89052",
    lat: 36.0119,
    lng: -115.0903,
    propertyType: "townhome",
    beds: 3,
    baths: 2,
    sqft: 1610,
    lotSqft: 2400,
    yearBuilt: 2001,
    listPrice: 295_000,
    daysOnMarket: 58,
    status: "active",
    listingRemarks:
      "Probate sale. Dated but clean — original kitchen, carpet throughout. No major repairs needed, just cosmetic refresh. Court confirmation may be required.",
    photos: [],
    priceHistory: [
      { date: isoDate(58), price: 315_000, event: "listed" },
      { date: isoDate(25), price: 295_000, event: "price_change" },
    ],
    comps: [
      { address: "2930 Palm Crescent Ln", soldPrice: 372_000, soldDate: isoDate(30), beds: 3, baths: 2, sqft: 1640, distanceMiles: 0.1 },
      { address: "2850 Coral Vine St", soldPrice: 365_000, soldDate: isoDate(48), beds: 3, baths: 2, sqft: 1590, distanceMiles: 0.3 },
      { address: "3001 Quiet Bay Ct", soldPrice: 358_000, soldDate: isoDate(65), beds: 3, baths: 2, sqft: 1600, distanceMiles: 0.5 },
    ],
    distressSignals: ["probate", "estate_sale", "long_dom", "major_price_reduction"],
    dealKillers: [],
    crimeScore: 88,
    schoolScore: 84,
    floodZone: false,
    neighborhoodGrowth: 9,
    rentalDemand: 68,
    investorCompetition: 36,
    estimatedRentMonthly: 2100,
    firstSeen: iso(15),
    lastScanned: iso(0),
  },
  {
    id: "lv-006",
    address: "118 Coppertree Ct",
    city: "Las Vegas",
    state: "NV",
    zip: "89107",
    lat: 36.1697,
    lng: -115.2089,
    propertyType: "duplex",
    beds: 4,
    baths: 4,
    sqft: 2000,
    lotSqft: 6500,
    yearBuilt: 1980,
    listPrice: 289_000,
    daysOnMarket: 47,
    status: "active",
    listingRemarks:
      "Absentee owner, tired duplex. Both units rentable now. Cosmetic updates recommended — paint, flooring. Great cash flow play or light flip.",
    photos: [],
    priceHistory: [
      { date: isoDate(47), price: 305_000, event: "listed" },
      { date: isoDate(18), price: 289_000, event: "price_change" },
    ],
    comps: [
      { address: "130 Coppertree Ct", soldPrice: 345_000, soldDate: isoDate(38), beds: 4, baths: 4, sqft: 2020, distanceMiles: 0.1 },
      { address: "204 Shadow Mountain Dr", soldPrice: 338_000, soldDate: isoDate(58), beds: 4, baths: 4, sqft: 1980, distanceMiles: 0.4 },
    ],
    distressSignals: ["absentee_owner", "vacant", "major_price_reduction"],
    dealKillers: [],
    crimeScore: 61,
    schoolScore: 55,
    floodZone: false,
    neighborhoodGrowth: 7,
    rentalDemand: 85,
    investorCompetition: 33,
    estimatedRentMonthly: 2600,
    firstSeen: iso(10),
    lastScanned: iso(0),
  },
];

export const SAMPLE_BUYERS: Buyer[] = [
  {
    id: "buyer-001",
    name: "Marcus Reed",
    company: "Reed Capital Homes",
    email: "marcus@reedcapital.example",
    phone: "702-555-0142",
    notes: "Experienced flipper, wants cosmetic deals in safe areas. Closes fast with cash.",
    active: true,
    createdAt: iso(90),
    buyBox: {
      minPrice: 150_000,
      maxPrice: 350_000,
      zips: [],
      cities: ["Las Vegas", "Henderson"],
      propertyTypes: ["single_family", "townhome", "condo"],
      strategies: ["flip"],
      minBeds: 2,
      minBaths: 2,
      maxRehabLevel: "moderate",
      minProfit: 35_000,
      minRoiPct: 12,
      avoidHighCrime: true,
    },
  },
  {
    id: "buyer-002",
    name: "Priya Nair",
    company: "Silver State Rentals",
    email: "priya@silverstaterentals.example",
    phone: "702-555-0188",
    notes: "Buy-and-hold landlord. Cash flow focus, will take heavier rehab for the right cap rate.",
    active: true,
    createdAt: iso(120),
    buyBox: {
      minPrice: 100_000,
      maxPrice: 320_000,
      zips: [],
      cities: [],
      propertyTypes: ["single_family", "duplex", "multi_family", "condo"],
      strategies: ["rental_hold", "brrrr", "wholesale"],
      minBeds: 2,
      minBaths: 1,
      maxRehabLevel: "heavy",
      minProfit: 0,
      minRoiPct: 8,
      avoidHighCrime: false,
    },
  },
  {
    id: "buyer-003",
    name: "Dev Okafor",
    company: "Skyline Flips",
    email: "dev@skylineflips.example",
    phone: "702-555-0210",
    notes: "High-volume flipper. Only wants A-class neighborhoods, bigger deals, fast assignments.",
    active: true,
    createdAt: iso(60),
    buyBox: {
      minPrice: 250_000,
      maxPrice: 500_000,
      zips: ["89052", "89149", "89135"],
      cities: ["Henderson", "Las Vegas"],
      propertyTypes: ["single_family"],
      strategies: ["flip"],
      minBeds: 3,
      minBaths: 2,
      maxRehabLevel: "moderate",
      minProfit: 50_000,
      minRoiPct: 15,
      avoidHighCrime: true,
    },
  },
];
